version: "2.0"

volumes:
  build-volume:

services:
  client:
    build:
      context: ./client
    volumes:
      - build-volume:/app/build
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_JWT_KEY=project-md-token
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_WS_URL=ws://localhost:5000
      - NODE_ENV=production
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    command: server /data
  rendererservice:
    build:
      context: ./services/renderer
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/Project-md
      - REDIS_URI=redis://host.docker.internal:6379
      - NODE_ENV=production
      - DEBUG=@Project.md/renderer:*
      - S3_URL=host.docker.internal
      - S3_PORT=9000
      - S3_USE_SSL=false
      - S3_ACCESS_KEY=accesskey
      - S3_SECRET_KEY=secretkey
    depends_on:
      - mongo
      - redis
      - minio
  server:
    build:
      context: ./server
    volumes:
      - build-volume:/app/build
    environment:
      - HTTP_PORT=5000
      - JWT_SECRET=beerandbongs
      - MONGODB_URI=mongodb://host.docker.internal:27017/Project-md
      - REDIS_URI=redis://host.docker.internal:6379
      - CLIENT_URL=http://localhost:5000
      - API_URL=http://localhost:5000
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=projectmdtest@gmail.com
      - EMAIL_PASSWORD=password
      - EMAIL_SECURE=false
      - EMAIL_FROM=no-reply@project-md.com
      - NODE_ENV=production
      - DEBUG=@Project.md:*
      - S3_URL=host.docker.internal
      - S3_PORT=9000
      - S3_USE_SSL=false
      - S3_ACCESS_KEY=accesskey
      - S3_SECRET_KEY=secretkey
    ports:
      - "5000:5000"
    depends_on:
      - client
      - mongo
      - redis
      - minio
