type Message {
    _id: ID!
    content: String!
    creator: User!
    type: MessageTypeEnum!
    subject: ID!
    createdAt: GraphQLDateTime!
}

enum MessageTypeEnum {
    user
    task
    organization
    project
}

type MessagesResponse {
    hasNextPage: Boolean!
    messages: [Message]!
}

input MessagesInput {
    type: MessageTypeEnum!
    subject: ID!
    page: Int!
    limit: Int!
}

input SubscribeMessageInput {
    type: MessageTypeEnum!
    subject: ID!
}

input SendMessageInput {
    type: MessageTypeEnum!
    subject: ID!
    content: String! @constraint(minLength: 1, maxLength: 3000)
}

type Query {
    messages(input: MessagesInput!): MessagesResponse!
}

type Mutation {
    sendMessage(input: SendMessageInput!): Boolean! @Auth(input: {required: true})
}

type Subscription {
    message(input: SubscribeMessageInput!): Message!
}