type User {
    _id: ID!
    username: String!
    email: String!
}

type AuthResponse {
    jwt: String!
    user: User!
}

# SIGN UP 
# ------------------------------------
input SignUpInput {
    username: String!
    email: String!
    password: String!
}

type SignUpResponse {
    data: AuthResponse
    error: Error
}

# SIGN IN
# ------------------------------------
input SignInInput {
    email: String!
    password: String!
}

type SignInResponse {
    data: AuthResponse
    error: Error
}

type Mutation {
    signUp(input: SignUpInput): SignUpResponse!
    signIn(input: SignInInput): SignInResponse!
}

type Query {
    me: User! @Auth(input: {required: true, populate: true})
}