type User {
    _id: ID!
    username: String!
    email: String!
}

# SIGN UP 
# ------------------------------------
input SignUpInput {
    username: String!
    email: String!
    password: String!
}

type SignUpData {
    jwt: String!
    user: User!
}

type SignUpError {
    message: String!
}

type SignUpResponse {
    data: SignUpData
    error: SignUpError
}

# SIGN IN
# ------------------------------------
input SignInInput {
    email: String!
    password: String!
}

type SignInData {
    jwt: String!
    user: User!
}

type SignInError {
    message: String!
}

type SignInResponse {
    data: SignInData
    error: SignInError
}

type Mutation {
    signUp(input: SignUpInput): SignUpResponse
    signIn(input: SignInInput): SignInResponse
}

type Query {
    me: User! @Auth(input: {required: true, populate: true})
}